### ISSUE TITLE
localization to Russian

### ISSUE THREAD

**Issue by DygDyg** [elvador/wow-spell-tooltips-code#2]
Good afternoon, you are creating a database manually or you can use a script to get it from your client. I would like to localize the plugin for myself. Is it possible to get spell descriptions directly from the client?

**Comment by elvador** [comment]
Hey, I scrape it from the ingame spell data with this addon:
https://github.com/elvador/SpellExport

**Comment by DygDyg** [comment]
where are plugins installed in vs code?

**Comment by elvador** [comment]
I'm sure Google will help you to find the answer.

**Comment by DygDyg** [comment]
https://drive.google.com/file/d/1LZu73OkU-L2eZBkq2DFrh5bmBYU5x-BW 
The Russian version may be useful :)

**Comment by elvador** [comment]
You've shared the link to a private file. 
Are you interested in permanently maintaining a Russian version of the spell data? This will require some changes to the extension from my side.

**Comment by DygDyg** [comment]
I would be ready to help, at least until I abandoned the game :)

Where is the best place to upload the file? I only know Russian file storages.

https://dropmefiles.com/bnLAF

**Comment by DygDyg** [comment]
https://drive.google.com/file/d/1LZu73OkU-L2eZBkq2DFrh5bmBYU5x-BW
